using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography;
using System.Text;

namespace RobloxCSharp.Extensions.Entities
{
	internal static class ComponentsLookupTemplate
	{
		// Fingerprint of the sorted component layout for this context.
		// Both sides (server and client) emit the same digest when built
		// from the same source; the runtime Ready handshake compares the
		// client's digest against the server's expectation and kicks on
		// mismatch. Computed over "FullName\n" lines so a rename, add,
		// remove, or namespace change flips the digest. Truncated to 16
		// hex chars — plenty against accidental collision, short enough
		// not to dominate every wire payload if we ever fold it in.
		internal static string ComputeBuildDigest(ContextModel ctx)
		{
			StringBuilder input = new();
			foreach (ComponentModel c in ctx.Components)
			{
				input.Append(c.FullName);
				input.Append('\n');
			}
			using SHA256 sha = SHA256.Create();
			byte[] hash = sha.ComputeHash(Encoding.UTF8.GetBytes(input.ToString()));
			StringBuilder hex = new();
			for (int i = 0; i < 8; i++) hex.Append(hash[i].ToString("x2"));
			return hex.ToString();
		}

		public static string Emit(ContextModel ctx)
		{
			StringBuilder sb = new();
			sb.AppendLine("// <auto-generated/> roblox-csharp-entities");
			sb.AppendLine("using Entities;");
			// `typeof(global::Code.Infrastructure.X)` carries the namespace
			// path through to the Lua emit verbatim — but the transpiler
			// only binds the bare type name as a local from CS.import. So
			// for typeof() we need `typeof(X)` (bare name), which needs
			// `using <namespace>;` at the top of the generated file. Pull
			// every component's containing namespace into the using set.
			HashSet<string> namespaces = new(StringComparer.Ordinal);
			foreach (ComponentModel c in ctx.Components)
			{
				string ns = c.NamespaceName;
				if (!string.IsNullOrEmpty(ns)) namespaces.Add(ns);
			}
			foreach (string ns in namespaces.OrderBy(s => s, StringComparer.Ordinal))
			{
				sb.AppendLine($"using {ns};");
			}
			sb.AppendLine();
			sb.AppendLine($"public static class {ctx.Name}ComponentsLookup");
			sb.AppendLine("{");
			for (int i = 0; i < ctx.Components.Count; i++)
			{
				sb.AppendLine($"\tpublic const int {ctx.Components[i].TypeName} = {i};");
			}
			sb.AppendLine($"\tpublic const int TotalComponents = {ctx.Components.Count};");
			sb.AppendLine($"\tpublic const string BuildDigest = \"{ComputeBuildDigest(ctx)}\";");
			sb.AppendLine();
			sb.AppendLine("\tpublic static readonly string[] componentNames =");
			sb.AppendLine("\t{");
			foreach (ComponentModel c in ctx.Components) sb.AppendLine($"\t\t\"{c.TypeName}\",");
			sb.AppendLine("\t};");
			sb.AppendLine();
			sb.AppendLine("\tpublic static readonly System.Type[] componentTypes =");
			sb.AppendLine("\t{");
			foreach (ComponentModel c in ctx.Components) sb.AppendLine($"\t\ttypeof({c.ClassName}),");
			sb.AppendLine("\t};");
			sb.AppendLine("}");
			return sb.ToString();
		}
	}
}
