using System.Text;

namespace RobloxCSharp.Extensions.Entities
{
	// Base partial — just the {Ctx}Entity shell with the inheritance line.
	// Removal side-effects ([Replicated] QueueRemove, [Unique] _Clear,
	// [EntityIndex] _Unregister) are no longer pre-fired here via a Destroy
	// override: the runtime fires {Ctx}Context._OnComponentRemoved (see
	// ContextTemplate) for every component stripped during RemoveComponent /
	// RemoveAllComponents, so a plain Entity:Destroy stays in sync with no
	// per-entity override to generate.
	//
	// EmitFlag and EmitValue (the per-component property emitters that
	// ComponentTemplate splices into each {Ctx}.{Component}.cs partial)
	// live in EntityTemplate.Flag.cs and EntityTemplate.Value.cs.
	internal static partial class EntityTemplate
	{
		public static string Emit(ContextModel ctx)
		{
			StringBuilder sb = new();
			sb.AppendLine("// <auto-generated/> roblox-csharp-entities");
			sb.AppendLine("using Entities;");
			sb.AppendLine();
			sb.AppendLine($"public sealed partial class {ctx.Name}Entity : Entity {{ }}");
			return sb.ToString();
		}
	}
}
