using System.Text;

namespace RobloxCSharp.Extensions.Entities
{
	// Emits a tiny C# class file for the synthesized {Name}Changed flag
	// of a [Watched] component. No attributes — the codegen synthesizes
	// the matching ComponentModel directly and never re-discovers this
	// class via attribute scan. The class only needs to exist so user
	// code can reference the type (`entity.Is{Name}Changed`) and so the
	// flag's static-singleton instantiation compiles.
	internal static class WatchedFlagClassTemplate
	{
		public static string Emit(ComponentModel source)
		{
			StringBuilder sb = new();
			sb.AppendLine("// <auto-generated/> roblox-csharp-entities");
			sb.AppendLine("using Entities;");
			sb.AppendLine();
			if (!string.IsNullOrEmpty(source.NamespaceName))
			{
				sb.AppendLine($"namespace {source.NamespaceName}");
				sb.AppendLine("{");
				sb.AppendLine($"\tpublic class {source.ClassName}Changed : IComponent {{ }}");
				sb.AppendLine("}");
			}
			else
			{
				sb.AppendLine($"public class {source.ClassName}Changed : IComponent {{ }}");
			}
			return sb.ToString();
		}
	}
}
